### ISSUE TITLE
Updates for recent releases

### ISSUE THREAD

**Issue by directentis1** [henryau53/xmind-crack-patch#9]
Based on suggestions from your crack (and some Mac OS), I patched it my own. 
https://github.com/directentis1/hctap-kcarc-dnimx/releases

Since XMind doesn't maintain regular updates, I thought it wouldn't take much time to give it a try.
I mainly use Linux so I will only support Linux if someone is interested.

Overall everything is fine, except for backend features like downloading [templates](https://cdn1.xmind.app/templates/templates_en-US_lqkg31y1.json) with index greater than [three](https://cdn1.xmind.app/templates/i18n_lqkg31y1.json) from the Create New Wizard.
(If anyone knows how to handle this case, please tell me ;))

**Comment by henryau53** [comment]
Wow, I just saw your comment. I've had so much to do recently that I rarely even check GitHub. Because of this, I've noticed a few bugs that need improvement in my version, and I haven't yet tested the other issue about Windows support.

Regarding what you mentioned about 'downloading templates with index greater than three from the Create New Wizard.' is that a feature introduced after v24 ? I haven't experienced v24 myself. For me, XMind is sufficient as it is now, so I haven't updated or maintained it.

**Comment by directentis1** [comment]
I'm not sure.. I bet the template selection feature is available from the 2020 version?
I tried debugging it, only valid username/auth token can download pro templates from their server.
The first 3 categories are each labeled "free" and "local", which are integrated locally in the default Installer.

Actually, if you build your own user-cases template  you often use, you don't really need them 😅

**Comment by John-nata** [comment]
@henryau53 Mate, don't download it! It's a bloody SPARKrat malware! 
That's why cracks and patches for software are so dodgy, just buy Xmind.
Lucky for you, I was searching for Xmind extensions/tools on Git.

Reports : [Cape Sandbox](https://vtbehaviour.commondatastorage.googleapis.com/8cdb95c297366cc38c09b6a0c3ca8619c65bf71407831a532c04acc94f873586_CAPE%20Sandbox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1723559701&Signature=DlZ1VI9a0hQi9M4nrRwVDNrCZ%2FSRHcNNNxdFcnX%2Bkr1KXpxBF0JC9G05I3U4Z0Uf45xQaMtRoGdzzQbiiCc25tgLXjbOkUSVeT11z5TLa7ou8QNW1MEF3ROH0O4IAxECoihzrEEsgidoWYjG31%2FkH92MEav8GTCZ2Dfg%2B7o%2F5MVDAkioVUe4d9pATvLbOef2m3jiJiO36880hqHxeS1hbgTq43thj4pHrr9X6wTUiPlRZWuPb60Po1PVziFhW%2BU9ZG%2FVHKHoIh6xBnYtxj1KwOVbmBcpl5CRKIknNCHHfQAdFq2fNgPE4GQVkH5B%2BH1FttMs1QgYvZqJ1GDShcxXhA%3D%3D&response-content-type=text%2Fhtml;) and [ZenBox](https://vtbehaviour.commondatastorage.googleapis.com/8cdb95c297366cc38c09b6a0c3ca8619c65bf71407831a532c04acc94f873586_Zenbox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1723559630&Signature=lVYjP4ZcgfAQtpRRJ%2BfeEjzvrTeIqkW0T1pRmscomkQWoLYQFK0TnpNlQTT1BQQRdQvr7YOMxClH4VmIC%2BPxRJi7tbxGp%2FYJTVejT2lVzJvWWPyhcfr3AAWQLUmAW9tq7GXTtw5mDkSmyRgzOrqpXrmLjF60COpVi7Agf3qq798xRnNe4UCozrSEclf6QpLcnvz%2FpfQG5j%2Fj8NgabbQ6zqbJtjI66KzHjTo%2B0xUVcph%2BYBYWUG7j5b30frl9KsDidZ7A3T4cIx79wBhqa34VvyLynD3SJHHBOx2zBiAgUjhSG5uEuzTRKIXRXHNSloXXNNWtoCfZACfjj7XNmkf2dQ%3D%3D&response-content-type=text%2Fhtml;)

@directentis1 I'll report your account mate

**Comment by henryau53** [comment]
> I'm not sure.. I bet the template selection feature is available from the 2020 version? I tried debugging it, only valid username/auth token can download pro templates from their server. The first 3 categories are each labeled "free" and "local", which are integrated locally in the default Installer.
> 
> Actually, if you build your own user-cases template you often use, you don't really need them 😅

I will try to find time this weekend to take a look at your version and the issues you described, to see if there are any solutions.

**Comment by directentis1** [comment]
> I will try to find time this weekend to take a look at your version and the issues you described, to see if there are any solutions.

Yeah... you could try.
It's just a simple patch (luckily they didn't mess with the Linux version) so there's nothing more.

About pro templates, I think hooking to another link to download or pre downloading them all and placing them in the same installed directory? 
But I bet that's not really necessary.

**Comment by John-nata** [comment]
Your patch is a damn SPARKrat malware, mate!
Explain why my VM behaves this like since I downloaded your file @directentis1
https://www.virustotal.com/gui/file/8cdb95c297366cc38c09b6a0c3ca8619c65bf71407831a532c04acc94f873586/behavior
![image](https://github.com/user-attachments/assets/dab3c394-fd64-4cd3-939f-b48521b34f00)
![Untitled](https://github.com/user-attachments/assets/d8014875-55c9-4780-98a0-42cebd377380)

**Comment by directentis1** [comment]
What's wrong with your head?

**Comment by henryau53** [comment]
I roughly looked at the code of xmind v24.04.10311. In version v23.08.02122, there are no templates that require pro permissions; these were updated after v23.08.02122.

The template you mentioned, which cannot be used if the index value is greater than 3, requires pro permissions, just like the [template](https://cdn1.xmind.app/templates/templates_en-US_lqkg31y1.json) JSON file you referred to above.

The general process is that if you choose a pro version template and it does not exist locally, it will fetch it from the official website with authentication information. As you said, if you wish to use pro version templates, you can try downloading the pro templates to your local storage, but you will always need a pro account to download the templates.

Moreover, my intention to crack the software was merely to utilize essential features in xmind for regular daily work, and I do not wish to excessively break it, as it is a very good product.

**Comment by henryau53** [comment]
@John-nata 

Wow, wow, I didn’t know exactly what happened, and I didn't install the version @directentis1 released because I didn’t see any commit records regarding modifications in his repository submissions. So I chose to install the official version, and I don’t have the authority to express any opinions on that.

However, I would like to remind you that this app.asar patch currently only applies to Linux and MacOS, and it does not work for Windows.

If you want to use it on Windows, you can refer to #8 and I am currently planning to take some time to look into it because it has already been delayed for too long.

**Comment by John-nata** [comment]
> What's wrong with your head?
@directentis1 I can guarantee there is nothing wrong with mine, as I don't spread malware like you do.

@henryau53 you'll be right, mate, nothing wrong with you at all! 😉
I'm not keen to install your patch, as I'm already using Obsidian and the free edition of Xmind (enough for my occasional needs).
I was looking for an Xmind tool on Git and stumbled upon your repo and directentis1's file. 
For some reason, I was pretty sure his file was containing a malware, and guess what? I was 100% right lol

**Comment by directentis1** [comment]
@henryau53 Yup, XMind is a good product and I really appreciate being able to use their product for free 😁
I notice to those patching on Windows, usually not patching the app.asar file but the dll file to disable license check/bypass it.

I no longer use Windows so I don't really care about those things. However, perhaps because Xmind's main market share comes from Windows, it's understandable that they have better security for it. 

Anyway, that's mine subjective opinion.

**Comment by directentis1** [comment]
Haha, I don't understand why they accused me of sending malware with these nonsense, unrelated screenshots 🤦‍♂️

Because app.asar is an electron pack, you can easily unpack it, and compare it to an original one with popular diff software (I use [Meld](https://meldmerge.org/)).

Actually, I learned that from your previous patches and realized that everything seems easier than I thought =)))

I patched it myself first and foremost for my own use, partly out of curiosity, so I post here to learn how everyone else did it :D

**Comment by directentis1** [comment]
@henryau53 
Just as you mentioned, I noticed that some may have changed from their server side. At least the library (public share mindmap) tab currently can not be displayed in the 2023 version.

![image](https://github.com/user-attachments/assets/d063eea7-853a-406a-b05c-f745ae66dbe3)

The available Template list is also much more limited in the 2023 version, about 30 (compared to the current version, [more than 100](https://cdn1.xmind.app/templates/templates_en-US_lqkg31y1.json)).
Perhaps Xmind sees that the template they have invested in building and curating is reasonable, so it belongs to a paid function 😁

![image](https://github.com/user-attachments/assets/75fcba35-faaf-4a79-88d2-6880c58454b8)
![image](https://github.com/user-attachments/assets/d8289362-ec6c-4bb3-8974-a640d52ee630)

**Comment by henryau53** [comment]
> @henryau53 Yup, XMind is a good product and I really appreciate being able to use their product for free 😁 I notice to those patching on Windows, usually not patching the app.asar file but the dll file to disable license check/bypass it.
> 
> I no longer use Windows so I don't really care about those things. However, perhaps because Xmind's main market share comes from Windows, it's understandable that they have better security for it.
> 
> Anyway, that's mine subjective opinion.

like you, I use Linux as my main machine, but I have tried the Windows version. The reason they use DLL to bypass updates instead of choosing app.asar is that Electron on Windows uses bytecode encryption to prevent cracking. At least to my knowledge, there is no way to crack bytecode app.asar on Windows.

Previously, a friend in #8 mentioned it was possible, and I just took a moment to check it out, but it turns out that's not the case; the pro features are not unlocked, which is a little disappointing.

If you like, you can try upgrading to the new version, as all the unlocking steps are in my commit log, and you've already seen it. As I mentioned in my README.md, it's for learning purposes only.
